'use client';
import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle, BookOpenCheck, CalendarDays, CheckCircle2, Database, Plus, Target, Users } from 'lucide-react';
import { getDashboardSummary } from '@/lib/attendance';
import { Section,Subject,TimetableEntry } from '@/types/attendance';
import { SectionSelector } from '@/components/SectionSelector';
import { StatCard } from '@/components/StatCard';
import { AttendanceForm } from '@/components/AttendanceForm';
import { SubjectTable } from '@/components/SubjectTable';
import { DetentionAlert } from '@/components/DetentionAlert';
import { Timetable } from '@/components/Timetable';
import { AttendanceChart } from '@/components/AttendanceChart';
import { LeaveSimulator } from '@/components/LeaveSimulator';
import { AttendanceAdvisor } from '@/components/AttendanceAdvisor';
import { OverallHealthChart } from '@/components/OverallHealthChart';

type CatalogSubject={id:string;name:string;code:string};
const todayIST=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export default function AttendancePage(){
 const [sections,setSections]=useState<Section[]>([]),[sectionId,setSectionId]=useState(''),[loadedSection,setLoadedSection]=useState(''),[subjects,setSubjects]=useState<Subject[]>([]),[catalog,setCatalog]=useState<CatalogSubject[]>([]),[futureDate,setFutureDate]=useState(''),[timetable,setTimetable]=useState<TimetableEntry[]>([]),[dataError,setDataError]=useState('');
 useEffect(()=>{setFutureDate(todayIST());fetch('/api/sections').then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setSections(d.sections);setSectionId(d.sections[0]?.id??'')}).catch(()=>setDataError('Timetable sections could not be loaded.'));},[]);
 useEffect(()=>{if(!sectionId)return;setDataError('');fetch(`/api/sections/${encodeURIComponent(sectionId)}/subjects`).then(r=>r.json()).then(s=>{if(s.error)throw Error();setCatalog(s.subjects||[]);const key=`roomwise-attendance:${sectionId}`;try{const saved=localStorage.getItem(key);setSubjects(saved?JSON.parse(saved):[])}catch{setSubjects([])}setLoadedSection(sectionId)}).catch(()=>setDataError('This section subject list could not be loaded.'));},[sectionId]);
 useEffect(()=>{if(!sectionId||!futureDate)return;fetch(`/api/sections/${encodeURIComponent(sectionId)}/timetable?startDate=${encodeURIComponent(futureDate)}&endDate=2026-11-29`).then(r=>r.json()).then(t=>{if(t.error)throw Error();setTimetable((t.entries||[]).map((e:any)=>({id:e.slot.id+'-'+e.date,sectionId,subject:e.subject?.name??e.slot.subjectId,date:e.date,startTime:e.slot.startTime,endTime:e.slot.endTime,room:e.slot.room,faculty:undefined,isPast:e.isPast})))}).catch(()=>setDataError('This section timetable could not be loaded.'));},[sectionId,futureDate]);
 useEffect(()=>{if(!sectionId||loadedSection!==sectionId)return;try{localStorage.setItem(`roomwise-attendance:${sectionId}`,JSON.stringify(subjects))}catch{}},[subjects,sectionId,loadedSection]);
 const changeSection=(id:string)=>{setLoadedSection('');setSubjects([]);setCatalog([]);setTimetable([]);setSectionId(id)};
 const entered=subjects.filter(s=>s.conducted>0),remainingClasses=timetable.filter((e:any)=>!e.isPast).length,summary=useMemo(()=>getDashboardSummary(entered,remainingClasses),[entered,remainingClasses]),section=sections.find(s=>s.id===sectionId),upcoming=timetable.filter((e:any)=>!e.isPast).slice(0,18);
 const addSubject=(s:Subject)=>setSubjects(prev=>prev.some(x=>x.id===s.id)?prev:[...prev,s]);
 const importSubject=(s:CatalogSubject)=>addSubject({id:s.id,name:s.name,attended:0,conducted:0});
 const importAll=()=>setSubjects(prev=>{const ids=new Set(prev.map(x=>x.id));return [...prev,...catalog.filter(c=>!ids.has(c.id)).map(c=>({id:c.id,name:c.name,attended:0,conducted:0}))]});
 const update=(id:string,patch:Partial<Pick<Subject,'attended'|'conducted'>>)=>setSubjects(prev=>prev.map(s=>s.id===id?{...s,...patch}:s));
 return <main className="min-h-screen bg-mist"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
   <section className="overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-soft sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-lime-300">Attendance command center</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Know where you stand. Plan what comes next.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">The room timetable now also drives section schedules. Enter your official attendance counts; the app calculates targets and previews future timetable impact.</p></section>
   <section className="mt-6"><div className="mb-3 flex items-center gap-2"><Users size={18}/><h2 className="font-bold">Select class section</h2></div>{dataError&&<p className="mb-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{dataError}</p>}{sections.length?<SectionSelector sections={sections} value={sectionId} onChange={changeSection}/>:<p className="text-sm text-slate-500">Loading sections…</p>}</section>
   <section className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="flex gap-3"><Database className="mt-0.5 shrink-0 text-blue-700" size={19}/><div><p className="font-bold text-blue-950">Unified timetable source</p><p className="mt-1 text-sm leading-6 text-blue-900">{section?.name} uses the structured timetable records shared with Roomwise. Course names are not expanded in the supplied room dataset, so single-letter entries are labeled as timetable codes rather than guessed subject names. Semester dates and holidays are planning configuration and should be verified locally.</p>{section?.sourcePdf&&<a className="mt-2 inline-block text-sm font-bold underline" href={section.sourcePdf} target="_blank" rel="noreferrer">Open source timetable PDF ↗</a>}</div></div></section>
   <section className="mt-6 surface p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Timetable subjects for {section?.name||'section'}</p><p className="text-sm text-slate-500">Import only the codes that correspond to attendance-bearing subjects in your official record.</p></div><button onClick={importAll} className="btn-soft"><Plus size={16}/>Import all codes</button></div><div className="mt-4 flex flex-wrap gap-2">{catalog.map(s=><button key={s.id} onClick={()=>importSubject(s)} disabled={subjects.some(x=>x.id===s.id)} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-700 hover:border-slate-400 disabled:opacity-40">+ {s.name}</button>)}</div></section>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Overall attendance" value={summary.conducted?`${summary.overallPercentage.toFixed(1)}%`:'—'} detail={summary.conducted?'Across entered subjects':'Enter official counts'} icon={Target}/><StatCard label="Classes conducted" value={summary.conducted} detail={`${summary.attended} attended`} icon={BookOpenCheck}/><StatCard label="Remaining timetable" value={remainingClasses} detail="Configured planning window" icon={CalendarDays}/><StatCard label="Required for 75%" value={summary.conducted?summary.classesTo75:'—'} detail="Consecutive attended classes" icon={Target}/><StatCard label="Required for 90%" value={summary.conducted?summary.classesTo90:'—'} detail="Consecutive attended classes" icon={CheckCircle2}/></section>
   {summary.conducted>0&&<div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 text-amber-700" size={19}/><div><p className="font-bold text-amber-900">75% checkpoint</p><p className="mt-1 text-sm text-amber-800">From the entered combined count, you need <strong>{summary.classesTo75}</strong> consecutive attended classes to reach 75%.</p></div></div></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-bold text-emerald-900">Browser-saved profile</p><p className="mt-1 text-sm text-emerald-800">Your entered counts are stored locally for this selected section, so a refresh does not wipe your dashboard.</p></div></div>}
   <div className="mt-6"><DetentionAlert show={summary.conducted>0&&summary.overallPercentage<75&&summary.classesTo75>summary.remainingClasses}/></div>
   <div className="mt-6"><AttendanceForm onAdd={addSubject} futureDate={futureDate} setFutureDate={setFutureDate}/></div>
   <div className="mt-6">{entered.length?<LeaveSimulator subjects={entered} timetable={timetable} planningDate={futureDate}/>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500">Enter at least one official attendance count to enable leave-impact simulation.</div>}</div>
   <div className="mt-6 grid gap-6 lg:grid-cols-[1.55fr_.95fr]"><SubjectTable subjects={subjects} onUpdate={update} onRemove={id=>setSubjects(p=>p.filter(s=>s.id!==id))}/><div className="grid gap-6">{entered.length?<><OverallHealthChart subjects={entered}/><AttendanceChart subjects={entered}/></>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500">Charts appear after you enter conducted-class counts.</div>}</div></div>
   <div className="mt-6"><Timetable entries={upcoming} sectionName={section?.name??'Selected section'}/></div>
   <footer className="py-8 text-center text-xs text-slate-400">Planning aid only. Verify official attendance, semester calendar, timetable changes, holidays, OD, and medical-leave rules with your institution.</footer>
 </div><AttendanceAdvisor subjects={entered} timetable={timetable} planningDate={futureDate} timetableVerified={section?.predictionEnabled===true}/></main>
}
