// @ts-nocheck
export const START=540, END=1010;
export const minute=s=>{if(!/^\d{2}:\d{2}$/.test(s))return NaN;const[h,m]=s.split(':').map(Number);return h<24&&m<60?h*60+m:NaN};
export const time=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export function istNow(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
export function dayOf(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return -1;const d=new Date(date+'T12:00:00Z');return Number.isNaN(+d)||d.toISOString().slice(0,10)!==date?-1:d.getUTCDay()}
export function evaluate(room,events,query){const start=minute(query.time),duration=Number(query.duration),end=start+duration,day=dayOf(query.date);const list=events.filter(x=>x.room===room.id&&x.day===day).sort((a,b)=>a.start-b.start||a.end-b.end);const overlaps=list.filter(e=>e.start<end&&e.end>start);const current=list.filter(e=>e.start<=start&&e.end>start);const next=list.find(e=>e.start>=start);const known=day>=1&&day<=5&&Number.isFinite(start)&&Number.isFinite(duration)&&duration>0&&start>=START&&end<=END;const missing=[];if(query.floor!=='all'&&query.floor!=='unknown'&&room.floor===null)missing.push('floor');if(query.ac!=='any'&&room.ac===null)missing.push('AC');if(query.people&&room.capacity===null)missing.push('capacity');const attrs=(query.floor==='all'||(query.floor==='unknown'?room.floor===null:String(room.floor)===query.floor))&&(query.ac==='any'||(room.ac!==null&&room.ac===(query.ac==='yes')))&&(!query.people||(room.capacity!==null&&room.capacity>=Number(query.people)));const free=known&&!overlaps.length;const match=free&&attrs&&room.type!=='lab';return{room,list,overlaps,current,next,start,end,known,free,match,attrs,missing,status:!known?'unknown':current.length?'busy':overlaps.length?'short':room.type==='lab'?'lab':!attrs?'filtered':'free',freeUntil:current.length?null:(next?.start??END)}}
// Small multinomial Naive Bayes intent models. Only constraint interpretation
// uses ML; occupancy is always calculated deterministically from source records.
const tokenize=s=>s.toLowerCase().match(/[a-z]+/g)||[];
function train(groups){const vocab=new Set;const classes=Object.entries(groups).map(([name,phrases])=>{const counts={};let total=0;for(const s of phrases)for(const word of tokenize(s)){vocab.add(word);counts[word]=(counts[word]||0)+1;total++}return{name,counts,total}});return text=>{const words=tokenize(text).filter(w=>vocab.has(w));if(!words.length)return null;const scores=classes.map(c=>({label:c.name,score:words.reduce((v,w)=>v+Math.log(((c.counts[w]||0)+1)/(c.total+vocab.size)),0)})).sort((a,b)=>b.score-a.score);const max=scores[0].score,den=scores.reduce((sum,x)=>sum+Math.exp(x.score-max),0);return{label:scores[0].label,confidence:1/den}}}
const floorModel=train({ground:['ground floor','ground level','ground floor classroom','downstairs on ground','lowest level','lowest floor','at street level','street level room','on the bottom floor','bottom level'],first:['first floor','first level','first floor classroom','level one','floor one','one flight up','up one flight of stairs','one floor above ground'],second:['second floor','second level','second floor classroom','level two','floor two','two flights up','up two flights of stairs','two floors above ground']});
const coolingModel=train({yes:['air conditioned','air conditioning','airconditioned room','a cooled room','a cool room','with cooling','with ac','ac room'],no:['without air conditioning','non ac room','no ac','without cooling','without ac','non air conditioned','uncooled room']});
const nums={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,twelve:12,fifteen:15,twenty:20,thirty:30,forty:40,fortyfive:45,sixty:60,ninety:90};
const addDay=(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
export function parseSearch(raw,base){if(typeof raw!=='string'||raw.trim().length<3||raw.length>500)throw Error('Describe a room, floor, or duration in a short sentence.');const original=raw.toLowerCase().replace(/-/g,' ');let s=original.replace(/\bforty five\b/g,'fortyfive').replace(/\b(one|two|three|four|five|six|seven|eight|nine|ten|twelve|fifteen|twenty|thirty|fortyfive|forty|sixty|ninety)\b/g,x=>nums[x]);s=s.replace(/\b(?:1|an?|one) and (?:a )?half (?:hours?|hrs?)\b/g,'1.5 hours').replace(/\bhalf (?:an? )?(?:hour|hr)\b/g,'30 minutes').replace(/\ba couple of hours\b/g,'2 hours').replace(/\ban? hour\b/g,'1 hour');const q={...base,floor:'all',ac:'any',people:''};const notes=[];let recognized=/\b(room|classroom|space|sit|study|work|team|group|free|empty|available)\b/.test(s);
if(/\b(projector|whiteboard|wheelchair|accessible|socket|wifi|wi fi|library|lab|laboratory|third|fourth|fifth|sixth|seventh|eighth)\b/.test(s))throw Error('That request includes a feature or floor not available in this room list. Use floor, AC, people, and duration.');
if(/\b(not on|except|other than|avoid)\b/.test(s))throw Error('Please name the floor you want, or select All floors. Excluded-floor searches are not supported.');
let f=s.match(/\b(ground|first|second|0|1|2)(?:st|nd)?\s*(?:floor|level)\b/)||s.match(/\b(?:floor|level)\s*(ground|first|second|0|1|2)\b/);if(f){q.floor=({ground:'0',first:'1',second:'2'})[f[1]]??f[1];recognized=true}else if(!/\b(any|all) floors?\b/.test(s)&&/\b(floor|level|downstairs|flight|flights|street)\b/.test(original)){const pred=floorModel(original);if(!pred||pred.confidence<.7)throw Error('Which floor do you mean? Choose ground, first, or second floor.');q.floor={ground:'0',first:'1',second:'2'}[pred.label];recognized=true}
if(/\b(any|all) floors?\b/.test(s))q.floor='all';
if(/\b(non ac|no ac|without ac|no air conditioning|without air conditioning|non air conditioned|without cooling)\b/.test(s)){q.ac='no';recognized=true}else if(/\b(ac|a c|air conditioned|air conditioning|airconditioned)\b/.test(s)){q.ac='yes';recognized=true}else if(/\b(cooled|cooling|uncooled|cool)\b/.test(s)){const pred=coolingModel(original);if(pred&&pred.confidence>.7){q.ac=pred.label;recognized=true}else throw Error('For cooling, please say AC or non-AC.');}
const durations=[...s.matchAll(/\b(\d+(?:\.\d+)?)\s*(hours?|hrs?|h|minutes?|mins?|m)\b/g)];if(durations.length){q.duration=durations.reduce((a,m)=>a+Number(m[1])*(m[2].startsWith('h')?60:1),0);recognized=true;if(!Number.isInteger(q.duration)||q.duration<1||q.duration>470)throw Error('Choose a stay between 1 and 470 whole minutes.');}else if(/\b(for|next)\s+(?:a few|several|some)\s+(?:hours?|minutes?)\b/.test(s))throw Error('Please specify a duration, such as 90 minutes or 2 hours.');
const people=s.match(/\b(\d+)\s*(?:people|persons?|students?|friends|members|seats)\b/)||s.match(/\b(?:team|group|party)\s+of\s+(\d+)\b/)||s.match(/\b(?:for|of)\s+(\d+)\s+of\s+us\b/);if(people){q.people=Number(people[1]);recognized=true;if(q.people<1||q.people>1000)throw Error('Use a group size between 1 and 1000.');}else if(/\b(team|group|friends)\b/.test(s))notes.push('Group size unspecified; capacity is not filtered.');
const today=istNow();if(/\btomorrow\b/.test(s))q.date=addDay(today.date,1);else if(/\btoday\b/.test(s))q.date=today.date;const date=s.match(/\b(20\d{2})[ /](\d{2})[ /](\d{2})\b/);if(date)q.date=`${date[1]}-${date[2]}-${date[3]}`;const weekday=s.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/);if(weekday){let delta=(['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].indexOf(weekday[1])-dayOf(today.date)+7)%7;if(/\bnext\s+(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/.test(s)&&delta===0)delta=7;q.date=addDay(today.date,delta)}
if(/\b(now|next)\b/.test(s)&&!weekday&&!/\btomorrow\b/.test(s)){q.date=today.date;q.time=today.time}const at=s.match(/\b(?:at|from|starting(?: at)?)\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/);if(at){let h=Number(at[1]),m=Number(at[2]||0);if(m>59||h>23||(at[3]&&(h<1||h>12)))throw Error('That start time is invalid. Try 11 am or 14:30.');if(at[3])h=h%12+(at[3]==='pm'?12:0);else if(h>=1&&h<=8&&!at[2])throw Error('Please include am or pm, for example at 2 pm.');q.time=time(h*60+m);recognized=true}
const until=s.match(/\buntil\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/);if(until){let h=Number(until[1]),m=Number(until[2]||0);if(h>23||m>59||(until[3]&&(h<1||h>12)))throw Error('That end time is invalid.');if(until[3])h=h%12+(until[3]==='pm'?12:0);else if(h>=1&&h<=8&&!until[2])throw Error('Please include am or pm in the end time.');q.duration=h*60+m-minute(q.time);if(q.duration<=0||q.duration>470)throw Error('The end time must follow the start time, within the same timetable day.');recognized=true}
if(/\b(quiet|silent)\b/.test(s))notes.push('Noise levels cannot be verified from a timetable.');if(!recognized)throw Error('Try a request such as “AC room on the ground floor for 2 hours.”');if(dayOf(q.date)<0)throw Error('Please choose a valid date.');return{query:q,notes}}
