'use client';
import { useState } from 'react';
import { Plus, CalendarDays } from 'lucide-react';
import { Subject } from '@/types/attendance';
export function AttendanceForm({ onAdd, futureDate, setFutureDate }: { onAdd:(s:Subject)=>void; futureDate:string; setFutureDate:(v:string)=>void }) {
  const [name,setName]=useState(''); const [attended,setAttended]=useState(''); const [conducted,setConducted]=useState(''); const [current,setCurrent]=useState('');
  function submit(e:React.FormEvent){ e.preventDefault(); const a=Number(attended), c=Number(conducted); if(!name.trim() || c<=0 || a<0 || a>c) return; onAdd({id:crypto.randomUUID(),name:name.trim(),attended:a,conducted:c,currentPercentage:current?Number(current):undefined}); setName('');setAttended('');setConducted('');setCurrent(''); }
  return <div className="rounded-2xl border border-line bg-white p-5 shadow-soft"><div className="mb-4"><h2 className="font-bold text-ink">Add attendance</h2><p className="text-sm text-slate-500">Counts are the source of truth; percentage is optional.</p></div><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="lg:col-span-2"><span className="label">Subject name</span><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Data Structures"/></label><label><span className="label">Attended</span><input className="field" type="number" min="0" value={attended} onChange={e=>setAttended(e.target.value)} placeholder="42"/></label><label><span className="label">Conducted</span><input className="field" type="number" min="1" value={conducted} onChange={e=>setConducted(e.target.value)} placeholder="48"/></label><label><span className="label">Current % <em>(optional)</em></span><input className="field" type="number" min="0" max="100" step="0.1" value={current} onChange={e=>setCurrent(e.target.value)} placeholder="87.5"/></label><div className="sm:col-span-2 lg:col-span-3"><label><span className="label"><CalendarDays size={14} className="inline mr-1"/>Planning date</span><input className="field" type="date" value={futureDate} onChange={e=>setFutureDate(e.target.value)}/></label></div><div className="sm:col-span-2 lg:col-span-2 flex items-end"><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-navy px-4 py-3 text-sm font-bold text-white hover:bg-slate-800"><Plus size={17}/>Add subject</button></div></form><style jsx>{`.label{display:block;margin-bottom:6px;font-size:12px;font-weight:700;color:#475569}.label em{font-style:normal;font-weight:500;color:#94a3b8}.field{width:100%;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;outline:none;background:#fff}.field:focus{border-color:#64748b;box-shadow:0 0 0 3px rgba(100,116,139,.12)}`}</style></div>
}
